site_name: sipgate Developer
site_description: Developer documentation for all sipgate APIs
theme:
  name: 'material'
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
